name: LinuxUbuntuBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Building RmlUI dep
      run: |
        git clone https://github.com/mikke89/RmlUi.git
        cd RmlUi
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
        cd ..
        
    - name: Installing deps
      run: |
        sudo apt-get -y update
        sudo apt-get -y install cmake make gcc
        sudo apt-get -y install libsdl2-dev libsdl2image-dev libglew-dev libglut-dev libglm-dev libassimp-dev
        
    - name: Makedir and navigate
      run: mkdir build && cd build
      
    - name: Cmake it
      run: cmake ..
      
    - name: Make it
      run: make
      
    - name: Upload artifacts
      uses: actions/download-artifact@v4.1.8
